version: '3'

services:

  mariadb:
    image: bitnami/mariadb:10.1
    volumes:
    - ${MARIADB_VOLUME:-mariadb-volume}:/bitnami:Z
    environment:
    - MARIADB_USER=${MYSQL_USER}
    - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    - MARIADB_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MARIADB_DATABASE=${MYSQL_DATABASE}
    - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB

  matomo:
    image: bitnami/matomo:3
    ports:
    - '80:80'
    depends_on:
    - mariadb
    volumes:
    - ${MATOMO_VOLUME:-matomo-volume}:/bitnami
    environment:
    - MATOMO_USERNAME=${MATOMO_USERNAME}
    - MATOMO_PASSWORD=${MATOMO_PASSWORD}
    - MATOMO_EMAIL=${MATOMO_EMAIL}
    - MATOMO_HOST=${MATOMO_HOST:-127.0.0.1}
    - MATOMO_DATABASE_USER=${MYSQL_USER}
    - MATOMO_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    - MATOMO_DATABASE_NAME=${MYSQL_DATABASE}
    - MARIADB_HOST=mariadb
    - MARIADB_PORT_NUMBER=3306
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - SMTP_PROTOCOL=${SMTP_PROTOCOL}

volumes:
  mariadb-volume:
  matomo-volume:
